version: 2

sources:
  - name: jaffle_shop
    database: RAW
    schema: JAFFILE_SHOP
    tables:
      - name: customers
      - name: orders

  - name: STRIP
    database: RAW
    schema: STRIP
    tables:
      - name: PAYMENT
      - name: T_TICKET_TRACK  
      
          
      